### PR TITLE
Enable AppVeyor integration for Windows tests

### PR DESCRIPTION
**Pull request by lisachenko**
It would be nice to run tests on Windows platform too to prevent errors on Windows platform

### CODE REVIEW

**Comment by lisachenko** [comment]
@TheCelavi Looks like we have issues on Windows platform :) Some commands could not be executed in tests. See PR details for appveyor...

And another part of errors is related to Win-slashes...

**Comment by lisachenko** [comment]
Looks like test results can be uploaded in jUnit format to AppVeyor https://github.com/appveyor/ci/issues/92#issuecomment-307242316

Need to add this as well.

**Comment by TheCelavi** [comment]
Ok, got it. Hate Windows! 

Will setup an env and fix those...

**Comment by lisachenko** [comment]
Oh, crap...

Errors
```
Symfony\Component\Filesystem\Exception\IOException: Failed to remove directory "C:\projects\goaop\tests\Fixtures\project\web/../var/cache/aspect\_annotations\f6": rmdir(C:\projects\goaop\tests\Fixtures\project\web/../var/cache/aspect\_annotations\f6): Directory not empty.
```
are present because Windows has a 260 symbols length limit for filenames and couldn't delete file for annotation that 260+ symbols long.

**Comment by lisachenko** [comment]
Woot! It's working :) Not ideal, but it's good start point for now.

**Pull request merged**
