### PR TITLE
[Compatibility] Allow Symfony 5 components.

### PR DESCRIPTION
**Pull request by func0der**

### CODE REVIEW

**Comment by func0der** [comment]
This change is for a 2.x release, since 3.x is yet to come, a quick 2.x would be nice :)

**Comment by func0der** [comment]
@lisachenko Do you have an idea how to fix that build check?

**Comment by lisachenko** [comment]
> Do you have an idea how to fix that build check?

Hmm, this can be an issue in the SymfonyInsight itself, as it tries to install version of package with incorrect PHP version.

**Comment by lisachenko** [comment]
Also, I don't see build results from Travis...

**Comment by lisachenko** [comment]
Tagged patch release 2.3.4

**Pull request merged**
