### PR TITLE
[Improvement] Decompose proxy generator

### PR DESCRIPTION
**Pull request by lisachenko**
This PR adds one more dependency, but makes core more readable and maintainable. Hope, that `zendframework/zend-code` is good enough to be used as code generator.

### CODE REVIEW

**Review by TheCelavi — COMMENTED** [review]
Didn't went into every detail, but seams legit. I like zend-code, why not?

**Comment by lisachenko** [comment]
@TheCelavi Thanks for reviewing! 
Only the disadvantage is that `zendframework/zend-code` has strange dependency on `zendframework/zend-eventmanager` (see https://github.com/zendframework/zend-code/issues/32#issuecomment-357039345) and `zendframework/zend-code` is not maintained last years (last commit was on `20 Oct 2017`). 

But all @Ocramius's tools depend on `zendframework/zend-code`, so this should be stable enough.

**Comment by TheCelavi** [comment]
> But all @Ocramius's tools depend on zendframework/zend-code, so this should be stable enough.

That means that you are betting on Ocramius's good health and well being? He is old, and I heard that he drinks a lot...  :D :D :D

**Comment by Ocramius** [comment]
Don't forget that I'm also affected by chronic laziness!

**Comment by lisachenko** [comment]
> That means that you are betting on Ocramius's good health and well being? He is old, and I heard that he drinks a lot... :D :D :D

> Don't forget that I'm also affected by chronic laziness!

Ah, it's acceptable for me, we can proceed with that, because we are lazy too! :arrow_up:  :smile: :beers:

**Pull request merged**
