### PR TITLE
Fix handling of special type hints, resolves #376

### LINKED ISSUE #376: [Bug] Incorrect handling of special type hints
Generated proxies don't support special typehints like `self`, `parent` because they are not builtin and are prefixed with leading slash like this: `\self`

Need to put them into exclusion list.

### PR DESCRIPTION
**Pull request by lisachenko**
This PR should fix handling of `self` and `parent` as type hints.

### CODE REVIEW

**Comment by lisachenko** [comment]
Implementation is wrong... My fault, need to rework this PR.

**Comment by lisachenko** [comment]
Hmm, this issue is very tricky. I want definitely to drop support for `parent` typehint, because calculation of parent name with proxy generation looks weird. And actually no-one uses `parent` as typehint, so it would be natural choice to drop this stuff.

I also have troubles with handling `self` in PHP5.6, because there is no way to query such information via reflection API. So I have big wish not to support this typehint for PHP5.6 and fix this issue only for master for PHP>=7.0. 

Even with PHP>=7.0 handling of `self` keyword requires knowledge of context, for example when grandparent has method with `self` as parameter typehint and we intercepting this method in child, then we should resolve what value should we use: should it be grandparent class or grandparent proxy (if method was intercepted in grandparent too).

**Comment by TheCelavi** [comment]
```php
class A_AopProxied 
{
    const X = 'value'

    public function foo($var = self::X) {}
    public function bar($var = self::class) {}
}

class A extends A_AopProxied
{
    public function foo($var = self::X) {  /* weaved */ }
    public function bar($var = self::class) { /* weaved */ }
}
```

I am trying to understand your dilema, is this the example that you are referring?

When using constant (e.g. `self::X`) seams that nothing should be resolved, it will work either way.

When using class name, well, proxied class should resolve to child class name, that is, `self::class` should resolve in, in our example, `A::class`.

If you are referring to this kind of type-hinting:

```php
class A
{
    public function foo(self $var) {}
}
``` 
My question is - does anyone ever write code like that? That is like really, really edge case (BS if you ask me). Either way, it seams like it should resolve to, as in our example, to A::class.

Or am I getting something wrong here?

**Comment by lisachenko** [comment]
@TheCelavi `self` typehint is typically used for return values to have fluent interface contract.  But dilemma with `self` is just combination of inheritance and interception rules.

So, let's start with following hierarchy:
```php
class A {
    public function setBar(): self {}
}

class B extends A {
    public function setBaz(): self {}
}
```

Then we want to intercept this method `setBaz()` from the class `B`. During proxy generation I will have full static reflection about class `B`, but I also need to rename this class to `B__AopProxied` and then I need to create proxy, keeping the signature for original method. This requires replacing `self` typehint with `B__AopProxied` FQN.

Hierarchy will be as following:
```php
class A {
    public function setBar(): self {}
}

class B__AopProxied extends A {
    public function setBaz(): self {}
}

class B extends B__AopProxied {
    public function setBaz(): B__AopProxied {}
}
```

But if I want to intercept method `setBar()` from the parent class `A` then generated code should refer to the class `A`, not to the proxied class:
```php
class A {
    public function setBar(): self {}
}

class B__AopProxied extends A {
    public function setBaz(): self {}
}

class B extends B__AopProxied {
    public function setBar(): A {}
    public function setBaz(): B__AopProxied {}
}
```

And finally, if this method `setBar()` will be intercepted in the both classes, then code should be generated like this.
```php
class A__AopProxied {
    public function setBar(): self {}
}

class A extends A__AopProxied {
    public function setBar(): A__AopProxied {}
}

class B__AopProxied extends A {
    public function setBaz(): self {}
}

class B extends B__AopProxied {
    public function setBar(): A__AopProxied {}
    public function setBaz(): B__AopProxied {}
}
```
All these rules for handling `self` keyword produce a lot of pain :) Summarize, to resolve `self` typehint I should check where it was declared, was it intercepted in parent or in child class and replace appropriately in generated proxy

**Comment by TheCelavi** [comment]
Thanks, I totally forgot about return types and type-hinting of those...

**Comment by lisachenko** [comment]
Same applied to parameter typehint:

```php
class A {
    public static function adjustInstance(self $instance) {}
}
```

**Comment by lisachenko** [comment]
What if replace `self`keyword with resolved value in an original class in advance?
```php
class A {
    public function setBar(): self {}
}

class B__AopProxied extends A {
    public function setBaz(): B {} // replaced `self` with FQN
}

class B extends B__AopProxied {
    public function setBaz(): B {} // just FQN from parent class, should work
}
```

**Comment by TheCelavi** [comment]
https://en.wikipedia.org/wiki/Occam%27s_razor

**Comment by lisachenko** [comment]
Ok, let's try to do this from another side, hope this won't be very complex :)

**Comment by lisachenko** [comment]
Just want to say: "Wow, PHP...", there are huge amount of places where `self` can appear.

1. Parameter type for method e.g. `public function foo(self $instance)`
2. Parameter type for closure, defined in the class: `$func = function (self $instance) {}`
3. Return type for method or closure in the class: `public function foo(): self {}`
4. Static method call: `self::someMethod()`
5. Class constant fetch: `$class = self::class; $const = self::SOME_CONSTANT;`
6. New instance creation: `new self();`
7. Instance of check: `$instance instanceof self`
8. Catch section (if `self` refers to instance of Exception): `catch (self $exception)`
9. Static property fetch: `$value = self::$someStaticVariable;`

I have implemented visitor that replaces `self` with FQN, but then I've discovered that 4) and 9) can fail for private properties and methods, because child class scope won't contain private properties and methods.

Interesting fact, that if you have any private static method, then you could always call it from the child class scope:

```php
class A {
    public function test() {
        echo B::bar();
    }

    private static function bar() {
        echo 'Yes';
    }
}

class B extends A {
}

$a = new B;
$a->test();
```
So for "method call" replacing `self` with child class name will work until child class try to declare the same private method, then everything will be broken.

For static property fetching results are more predictable: it's impossible to replace `self` with child class, because if property was declared as private then fatal will be raised:

```php
class A {
    private static $foo = 42;
    public function test() {
        echo B::$foo;
    }
}

class B extends A {
}

$a = new B;
$a->test();
// Fatal error: Uncaught Error: Cannot access property B::$foo
```
For this case it will be easier to leave `self::$someProperty` in code as is and do not transform such nodes. Summarize everything 1)-8) are implemented and 9) should not be transformed.

PR will be updated soon...

**Comment by lisachenko** [comment]
Implemented via AST-transformation of original class

This also resolves old issues #348, #139,  #130, #94, because `self` is replaced with resolved class name now.

**Pull request merged**
