### PR TITLE
Fix cache permissions

### PR DESCRIPTION
**Pull request by RLasinski**
This pull request is related to issue #275.

### CODE REVIEW

**Comment by asquel** [comment]
@lisachenko : could you accept this one ? 
it's really important, nothing works in symfony if this one is not accepted !

**Comment by lisachenko** [comment]
@asquel @RLasinski Sorry for the delay, I'm busy at the moment.

I'm going to review this change and think about permissions tomorrow. Anyway, default cache rights 0777 is definitely incorrect (see https://github.com/goaop/framework/pull/276/files#diff-d5bfab16e0917c94b33843f7c99fcf08R55)

**Comment by lisachenko** [comment]
Closed via rebase in https://github.com/goaop/framework/commit/3079dcaef87e35aeac99946d7176838846a77e84

**Comment by lisachenko** [comment]
Thanks!

**Pull request closed without merging**
